from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def write_report(report: dict[str, Any], output: Path, candidate_limit: int = 5000) -> None:
    browser_report = {**report, "candidates": report["candidates"][:candidate_limit]}
    browser_report["html_candidate_count"] = len(browser_report["candidates"])
    payload = json.dumps(browser_report, ensure_ascii=False).replace("</", "<\\/")
    html = """<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dedup PoC</title>
<style>:root{color-scheme:dark;--bg:#0d1117;--panel:#161b22;--line:#30363d;--fg:#e6edf3;--muted:#8b949e;--green:#3fb950;--red:#f85149;--yellow:#d29922}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.45 system-ui,sans-serif}header{position:sticky;top:0;background:#0d1117f2;border-bottom:1px solid var(--line);padding:16px 22px;z-index:2}h1{font-size:20px;margin:0 0 10px}.summary{display:flex;gap:14px;flex-wrap:wrap;color:var(--muted)}.controls{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}input,select{background:var(--panel);color:var(--fg);border:1px solid var(--line);padding:8px;border-radius:6px}input{min-width:280px;flex:1}main{padding:16px 22px}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px;margin-bottom:14px}.metric,.row{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:12px}.metric b{font-size:20px;display:block}.row{margin-bottom:8px}.top{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.badge{padding:2px 7px;border:1px solid var(--line);border-radius:999px}.same_identity{color:var(--green)}.different_identity{color:var(--red)}.defer,.insufficient_evidence{color:var(--yellow)}code{color:#79c0ff}.titles{font-size:16px;margin:8px 0}.muted{color:var(--muted)}details{margin-top:7px}summary{cursor:pointer}@media(max-width:700px){header,main{padding-left:10px;padding-right:10px}input{min-width:100%}}</style></head>
<body><header><h1>Dedup retrieval + scoring PoC</h1><div class="summary" id="summary"></div><div class="controls"><select id="scope"><option value="items">Labeled tasks (OOF scores)</option><option value="candidates">Top candidate sample (full-fit scores)</option></select><input id="q" placeholder="Search title, ID, frame…"><select id="gold"><option value="">All gold labels</option><option>same_identity</option><option>different_identity</option><option>insufficient_evidence</option><option>excluded</option><option>unlabeled</option></select><select id="retrieved"><option value="">Retrieved or missed</option><option value="yes">retrieved</option><option value="no">missed</option></select><select id="outcome"><option value="">All score outcomes</option><option value="correct">correct</option><option value="wrong">wrong</option><option value="defer">defer</option></select></div></header><main><section class="metrics" id="metrics"></section><section id="rows"></section></main>
<script>const report=__DATA__;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const pct=x=>x==null?'n/a':(100*x).toFixed(1)+'%';
document.querySelector('#metrics').innerHTML=`<div class="metric"><b>${report.dataset.tasks}</b>labeled task pairs</div><div class="metric"><b>${report.dataset.unique_views}</b>unique entity views</div><div class="metric"><b>${pct(report.retrieval.positive_recall)}</b>positive retrieval recall</div><div class="metric"><b>${report.retrieval.candidate_pairs}</b>candidate pairs (${pct(report.retrieval.candidate_fraction)})</div><div class="metric"><b>${report.scoring.roc_auc.toFixed(3)}</b>grouped OOF ROC AUC</div><div class="metric"><b>${pct(report.scoring.decided_accuracy)}</b>decided-pair accuracy</div><div class="metric"><b>${pct(report.scoring.coverage)}</b>automatic coverage</div><div class="metric"><b>${pct(report.scoring.auto_merge_precision)}</b>merge precision</div>`;
function render(){let scope=document.querySelector('#scope').value,source=scope==='candidates'?report.candidates:report.items,q=document.querySelector('#q').value.toLowerCase(),g=document.querySelector('#gold').value,r=document.querySelector('#retrieved').value,o=document.querySelector('#outcome').value;let rows=source.filter(x=>(!g||x.gold===g)&&(!r||(r==='yes')===x.retrieved)&&(!q||JSON.stringify(x).toLowerCase().includes(q)));if(o)rows=rows.filter(x=>o==='defer'?x.prediction==='defer':o==='correct'?x.prediction===x.gold:x.prediction&&x.prediction!=='defer'&&x.prediction!==x.gold);document.querySelector('#summary').textContent=`Showing ${rows.length}/${source.length} · merge ≥ ${report.scoring.merge_threshold.toFixed(3)} · separate ≤ ${report.scoring.separate_threshold.toFixed(3)}`;document.querySelector('#rows').innerHTML=rows.map(x=>`<article class="row"><div class="top"><code>${x.short_id}</code><span class="badge">${esc(x.type)}</span><span class="badge">${esc(x.frame)}</span><span class="badge ${x.gold}">gold: ${esc(x.gold)}</span><span class="badge ${x.prediction}">score: ${esc(x.prediction??'audit-only')}</span><span class="badge">${x.retrieved?'retrieved':'MISSED'}</span></div><div class="titles">${esc(x.left_title||'(untitled)')} ↔ ${esc(x.right_title||'(untitled)')}</div><div class="muted">channels: ${esc(x.channels.join(', ')||'none')} · score source: ${esc(x.probability_kind??'none')} · p(same): ${x.probability_same==null?'n/a':x.probability_same.toFixed(4)}</div><details><summary>Features</summary><pre>${esc(JSON.stringify(x.features,null,2))}</pre><div class="muted">${esc(x.stratum)}</div></details></article>`).join('')}</script></body></html>"""
    output.write_text(html.replace("__DATA__", payload), encoding="utf-8")
